/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#5a656b',
        'primary-fixed-dim': '#bdc8d0',
        'surface-container-high': '#2a2a2a',
        'inverse-surface': '#e4e2e2',
        'on-primary-fixed': '#131d23',
        'primary-container': '#d7e2ea',
        'on-error': '#690005',
        'secondary-container': '#444953',
        'on-primary': '#273238',
        'on-surface': '#e4e2e2',
        'tertiary-fixed': '#f6decb',
        'tertiary-container': '#f4dcc9',
        'on-background': '#e4e2e2',
        'surface-container-highest': '#353535',
        outline: '#8d9194',
        surface: '#131314',
        'surface-variant': '#353535',
        'on-tertiary-fixed-variant': '#544436',
        'error-container': '#93000a',
        'surface-container': '#1f2020',
        error: '#ffb4ab',
        'surface-container-low': '#1b1c1c',
        'surface-bright': '#393939',
        'inverse-on-surface': '#303031',
        'on-surface-variant': '#c4c7ca',
        'on-secondary': '#2c3139',
        primary: '#fcfdff',
        'surface-dim': '#131314',
        background: '#131314',
        'surface-container-lowest': '#0e0e0f',
        tertiary: '#fffcff',
        'on-secondary-fixed': '#171c24',
        'outline-variant': '#43474a',
        'secondary-fixed': '#dee2ee',
        'on-primary-fixed-variant': '#3e484f',
        'surface-tint': '#bdc8d0',
        'on-secondary-container': '#b4b8c4',
        'on-tertiary-container': '#716051',
        secondary: '#c2c6d2',
        'on-secondary-fixed-variant': '#424750',
        'primary-fixed': '#d9e4ec',
        'inverse-primary': '#556067',
        'secondary-fixed-dim': '#c2c6d2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        gutter: '24px',
        'container-max': '1440px',
        unit: '8px',
        'stack-overlap': '100px',
        'margin-mobile': '20px',
      },
      fontFamily: { kanit: ['Kanit', 'sans-serif'] },
      maxWidth: { 'container-max': '1440px' },
    },
  },
  plugins: [],
};
